{% set name = "dask-ml" %}
{% set version = "2025.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-","_") }}-{{ version }}.tar.gz
  sha256: b31caeb5f603f9537ffa34bd247e0e1fcefda7c007631260f8abdee49f89b1e1

build:
  number: 0
  # numba isn't available on s390x
  skip: True  # [py<310 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    # dask-ml requires dask with dask.array and dask.dataframe
    - dask >=2025.1.0
    - dask-glm >=0.2.0
    - distributed >=2025.1.0
    - multipledispatch >=0.4.9
    - numba >=0.51.0
    - numpy >=1.24.0
    - packaging
    - pandas >=2.0
    - python
    - scikit-learn >=1.6.1
    - scipy

test:
  imports:
    - dask_ml
    - dask_ml.cluster
    - dask_ml.decomposition
    - dask_ml.feature_extraction
    - dask_ml.linear_model
    - dask_ml.metrics
    - dask_ml.model_selection
    - dask_ml.preprocessing
    - dask_ml.utils
    - dask_ml.wrappers
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/dask-ml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Distributed and parallel machine learning using dask.
  description: |
    Dask-ML provides scalable machine learning in Python
    using Dask alongside popular machine learning libraries like Scikit-Learn, XGBoost, and others.
  doc_url: https://ml.dask.org
  dev_url: https://github.com/dask/dask-ml

extra:
  recipe-maintainers:
    - TomAugspurger
    - jrbourbeau
