travis:
  secure:
    BINSTAR_TOKEN: UGh0oiZHBR0eTCrCl9GoRWeGuhLjHlwpxXb5Do//ISzNIGqc8GXS5hFs14PxZ2DUCNBLhp3A1gcTP1VuuVd0JT7GEoPOIZ2+FpIhiLnsGI82evB105q59EUjSDuVfMWGDMwI79DhnO/1tVNYDPcxjTJMFFnfFSJDlMupOdYzah05CgtlKNESGBizNg+yIyPu9A0sFZdYeFPpB0ru3YUmqqcskWYuGiKAvvDG6hJlJYEbDkgIrKy9pcY+JEiKOnQANpfgM0QgkfU7pn7bMKv0rQJl8wK+rlcnGPoaA2QUDGH19qiuZ1qASd3hX3HGmq64IOf88+TQHXBrb4LIngQOLTB7OvM/kJ0CHr3tIOYAKZFMlrSPjqs3h0xXihg/6S9chSKgHvD1xVk7efTbvLGHt3RdvYjcSMLpK3iZPc8U08bBKc9PraC2BWOAsyC2TFeiQhRS/wEDju0lMF9lCYyl8trJaCgE+qStrbAKIaCNHxu0V5mGc3LW4EMWNIfMeEExeA3bOT+IvgFnmDMKeurN/dXZBz6C5sPtaK4qUqGK4tFVcjAtCv7/js8r4nIla/eN76H0EhS3OWhqHnB4eIdj6P9GvAeyvbeSQlGgnfqTHiTMYExG0U3luAxcTIXCw+DU+muhJ7uMHUDlOaXqRhawXcwCsN9hznxGef3FyC9461M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
