travis:
  secure:
    BINSTAR_TOKEN: Ldi0hiye4zzmYgEr7uGjG61vpLmblpmRBnllWH7XWTC8b8Z8MADkpdK6yp7FdrOwjwHaG/5zVP+OeApoQGlq2BoCyCsLQpvEzDYEYAfXemYKCa/3rD5vFATwD8cP6KSV3rY2mxjbHiSFftiZLM4rOQFqJJ3VPFlnjl1+VufpEhl/Ec6FWCDqKU0Rx2PRr8FCvGTH+7u7OIo6ATqbEUrTtRnNNM3TdDTUkwiIS2+lq4SXWM8eSFiL/qiIwY0fEhxR9vrCx07dX0eiGwUAyr2+q1J8tVxlTdobYsZoviZ+oFSpdbI44XU64OkMUiZomnR1cmN+PPVcS3DtiTd7071zuybcp2NEPlBgalH9hrDCTmvxS3F+tcxlZyRYBDUvvphymIbNjJISV7zuEaOjCgTbIerGeh6NpNdS1V5IRSI+jMw5PXyYE03l8WhB00dufWqgIx5XDTb38ImGkWzu51QLb3qpmCNabNeQHlB5CauRb5bJu12ne6NCaqRL2z7QtV1qA/fONqdfGh/bftBY8FvaDXFzTVwJM9tcuVHNaROtHIrksEkLHpBE2zglM53DHj7azpQDbJyNMyB/cTTUwn1epUTCNy+zqix62dVFrAjNi7xfxF4iFt3rpyhtdgtJA/646wGKRNE4tKZ+1MD6gsANo/oYwc3ygJNRPMt4/4/moIo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
